targets:
  - name: build
    command: swift build -c release --disable-sandbox
  - name: format
    command: swiftformat .
  - name: clean
    command: rm -rf .build
  - name: generate_makefile
    command: swift run stencly render -t Makefile.stencil -d ./Makefile.yaml -o ./Makefile
