prefix ?= /usr/local
bindir = $(prefix)/bin

{% for target in targets %}
{{ target.name }}:{% for dep in target.dependencies %} {{ dep }}{% endfor %}
	{{ target.command }}
{% endfor %}

.PHONY:{% for target in targets %} {{ target.name }}{% endfor %}
