prefix ?= /usr/local
bindir = $(prefix)/bin
{% for target in targets %}

{{ target.name }}:{% for dep in target.dependencies %} {{ dep }}{% endfor %}
	{% for command in target.command %}
	{{ command }}
	{% endfor %}
{% endfor %}

list:
	@echo Available commands:
	{% for target in targets %}
	@echo - {{ target.name }}
	{% endfor %}

.PHONY:{% for target in targets %} {{ target.name }}{% endfor %} list
