---
targets:
  - name: install
    dependencies: [build]
    command:
      - install ".build/release/stencil" "$(bindir)"
  - name: uninstall
    command:
      - rm -rf "$(bindir)/stencil"
  - name: build
    command:
      - swift build -c release --disable-sandbox
  - name: format
    command:
      - swiftformat .
  - name: clean
    command:
      - rm -rf .build
  - name: makefile
    command:
      - swift run stencil render -t Templates/Makefile.stencil -d Templates/Makefile.yaml -o ./Makefile
  - name: archive
    dependencies: [build]
    command:
      - mkdir -p archive
      - tar -cvzf ./archive/stencil-cli.tar.gz  -C .build/release/ stencil
